sudo: true
language:
- python
python:
  - "2.7"
before_install:
 - "git clone https://github.com/valermor/galen-api-ports.git"
 - "git clone https://github.com/valermor/galen-sample-py-tests.git"
 - chmod +x install_thrift.sh
 - chmod +x install_galenpy.sh
 - ./install_thrift.sh
install:
 - "chmod 700 install_galenpy.sh"
 - "./install_galenpy.sh"
 - "pip install -r galen-sample-py-tests/requirements.txt"
script: './run_tests.sh'
