language:
- python
python:
  - "2.7"
before_install:
 - "git clone https://github.com/valermor/galen-api-ports.git"
 - "git clone https://github.com/valermor/galen-sample-py-tests.git"
# command to install dependencies
install:
 - "./install_galenpy.sh"
 - "pip install -r galen-sample-py-tests/requirements.txt"
script: './run_tests.sh'
